algoritmo "conteate10"
// Função :
// Autor :
// Data : 18/10/2020
// Seção de Declarações 
var
valor, salto, contador: inteiro

inicio
contador <- 0
Escreva("Quer contar até quanto?")
Leia(valor)
Escreva ("Qual será o valor do salto?")
Leia (salto)
Enquanto (contador <= valor) faca
         EscrevaL (contador)
         contador <- contador + salto
FimEnquanto
Escreval ("terminei de contar")
fimalgoritmo
